# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Un Simple Dev
email: guillermo.lobos.parada@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Estudiante de Informática, me encanta el desarrollo de software y el
  aprendizaje de diversos temas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://unforgivencl.github.io/" # the base hostname & protocol for your site
twitter_username: unsimpledev
github_username:  UnforgivenCL

# Build settings
markdown: kramdown
